/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardArea: typeof import('./src/components/areas/DashboardArea.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LeftArea: typeof import('./src/components/areas/LeftArea.vue')['default']
    MotivationWidget: typeof import('./src/components/widgets/MotivationWidget.vue')['default']
    PlaceholderWidget: typeof import('./src/components/widgets/PlaceholderWidget.vue')['default']
    RightArea: typeof import('./src/components/areas/RightArea.vue')['default']
    TimeWidget: typeof import('./src/components/widgets/TimeWidget.vue')['default']
    TodoWidget: typeof import('./src/components/widgets/TodoWidget.vue')['default']
    WeatherWidget: typeof import('./src/components/widgets/WeatherWidget.vue')['default']
    WidgetArea: typeof import('./src/components/areas/WidgetArea.vue')['default']
    WidgetAreaHighOrder: typeof import('./src/components/widgets/WidgetAreaHighOrder.vue')['default']
  }
}
