/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    TodoWidget: typeof import('./src/components/widgets/TodoWidget.vue')['default']
    WeatherWidget: typeof import('./src/components/widgets/WeatherWidget.vue')['default']
    WidgetArea: typeof import('./src/components/areas/WidgetArea.vue')['default']
    WidgetAreaHighOrder: typeof import('./src/components/widgets/WidgetAreaHighOrder.vue')['default']
  }
}
